# 작업명
name: CD Pipeline
on:
  push:
    branches:
      - 'develop'
      - 'main'

jobs:
  CD:
    runs-on: ubuntu-latest
    env:
      RESOURCE_PATH: ./src/main/resources/application.yml
    steps:
      ## Project JDK 17 Setting
      - name: Checkout
        uses: actions/checkout@v3
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Set yml file
        uses: microsoft/variable-substitution@v1
        with:
          files: ${{ env.RESOURCE_PATH }}
        env:
          spring.datasource.url: ${{ secrets.DEV_SERVER_DNS }}
          spring.datasource.username: ${{ secrets.DB_USERNAME }}
          spring.datasource.password: ${{ secrets.DB_PASSWORD }}
          spring.security.oauth2.client.registration.Kakao.client-id: ${{ secrets.KAKAO_CLIENT_ID }}
          spring.security.oauth2.client.registration.Kakao.client-secret: ${{ secrets.KAKAO_CLIENT_SECRET }}
          coolsms.api.number: ${{ secrets.FROMNUMBER }}
          coolsms.api.secret: ${{ secrets.COOLSMS_API_SECRET }}
          coolsms.api.key: ${{ secrets.COOLSMS_API_KEY }}
          cloud.aws.s3.bucket: ${{ secrets.S3_BUCKET }}
          cloud.aws.credentials.access-key: ${{ secrets.AWS_ACCESS_KEY_ID }}
          cloud.aws.credentials.secret-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          cloud.aws.region.static: ap-northeast-2

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      - name: Build with Gradle
        uses: gradle/gradle-build-action@v2
        with:
          arguments: build
          cache-read-only: ${{ github.ref != 'refs/heads/main' && github.ref != 'refs/heads/develop' }}

      # Login to ghcr
      - name: Login to ghcr
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: pinetree2
          password: ${{ secrets.GHCR_TOKEN }}

      # Docker 빌드 생성 및 푸시
      - name: dev Docker build & push
        if: contains(github.ref, 'main') || contains(github.ref, 'develop')
        run: |
          docker build -f Dockerfile -t ghcr.io/onion-city/whatssue_be_v2/whatssue:latest .
          docker push ghcr.io/Onion-City/Whatssue_BE_v2/whatssue:latest


      # 개발서버 SSH접속 및 배포
      - name: Deploy
        uses: appleboy/ssh-action@master
        id: deploy
        if: contains(github.ref, 'main') || contains(github.ref, 'develop')
        with:
          host: ${{ secrets.DEV_SERVER_DNS }}
          username: ${{ secrets.DEV_SERVER_USER }}
          password: ${{ secrets.DEV_SERVER_PASSWORD }}
          port: ${{ secrets.DEV_SERVER_SSH_PORT }}
          script: |
            echo "${{ secrets.GHCR_TOKEN }}" | sudo docker login ghcr.io -u pinetree2 --password-stdin
            if [ "$(docker ps -aq -f name=whatssue-be)" ]; then
                sudo docker stop whatssue-be
                sudo docker rm whatssue-be
            fi
            
            if [ "$(docker images -q ghcr.io/onion-city/whatssue_be_v2/whatssue)" ]; then
            sudo docker rmi ghcr.io/onion-city/whatssue_be_v2/whatssue
            fi
            sudo docker pull ghcr.io/onion-city/whatssue_be_v2/whatssue:latest
            sudo docker stop whatssue-be
            sudo docker rm whatssue-be
            sudo docker run -d -p 8080:8080 --name whatssue-be ghcr.io/onion-city/whatssue_be_v2/whatssue:latest
            sudo docker image prune -a -f
